# Generated by Django 4.1.1 on 2022-10-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carrousel_heropage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='carousel_link',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
