# Generated by Django 4.1.1 on 2022-10-18 16:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('home', '0004_carrousel_carousel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('carrousel_body', wagtail.fields.RichTextField()),
                ('carrousel_cta', models.CharField(max_length=100)),
                ('carousel_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
