# Generated by Django 4.1.1 on 2022-11-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexcontainer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexContainer',
        ),
    ]
